Repository XPEHO/xpeapp_admin, pull requests merged in 2024-12, with the labels that each got.

#125 fix(icon_text): Change text and icon for more readability
  lib/presentation/pages/qvst/content/qvst_content_home.dart
  lib/presentation/pages/qvst/content/qvst_content_theme.dart
Labels: bug :bug:

#128 fix(dateSpacing): fix the date spacing
  lib/presentation/pages/qvst/widgets/qvst_create_campaign.dart
Labels: bug :bug:

#131 fix(referentialQuestionsProposal): use providers instead of state
  lib/data/state/response_reference_selection_notifier.dart
  lib/presentation/pages/qvst/widgets/response_reference_widget.dart
  lib/providers.dart
  test/data/state/response_reference_selection_notifier_test.dart
Labels: bug :bug:

#130 fix(referentialQuestions): fix the referential questions changing not…
  lib/data/state/response_reference_selection_notifier.dart
  lib/presentation/pages/qvst/widgets/response_reference_widget.dart
  lib/providers.dart
  test/data/state/response_reference_selection_notifier_test.dart
Labels: bug :bug:

#132 feat(reload_and_action): Add and improve actions and layout
  lib/data/state/qvst_menu_notifier.dart
  lib/presentation/pages/home_page.dart
  lib/presentation/pages/login_page.dart
  lib/presentation/pages/newsletters/newsletters_page.dart
  lib/presentation/pages/qvst/content/qvst_content_campaign.dart
  lib/presentation/pages/qvst/content/qvst_content_home.dart
  lib/presentation/pages/qvst/content/qvst_content_responses.dart
  lib/presentation/pages/qvst/content/qvst_content_stats.dart
  lib/presentation/pages/qvst/content/qvst_content_theme.dart
  lib/presentation/pages/qvst/content/qvst_content_update_response_repo.dart
  lib/presentation/pages/qvst/content/qvst_table_view.dart
  lib/presentation/pages/qvst/qvst_add_page.dart
  lib/presentation/pages/qvst/qvst_detail_page.dart
  lib/presentation/pages/qvst/widgets/qvst_choice_theme.dart
  lib/presentation/pages/qvst/widgets/qvst_create_campaign.dart
  lib/presentation/pages/qvst/widgets/qvst_import_question_file_dialog.dart
  lib/presentation/widgets/qvst/qvst_status_of_campaign_and_button.dart
  test/data/state/qvst_menu_notifier_test.dart
Labels: enhancement :rocket:

#136 docs(check): Ensure a good documentation for new arrivals on the project
  README.md
Labels: other
